### ISSUE TITLE
[BUG] Cannot find the official documentation, CONTRIBUTING.md, LICENSE.

### ISSUE THREAD

**Issue by Accord33** [Sunwood-ai-labs/AIRA#4]
I could not find the official documentation, CONTRIBUTING.md, and LICENSE among the links posted in the README.
Could you please add those?
I am very interested in the official documentation.

READMEに貼ってあるリンクの内、公式ドキュメント、CONTRIBUTING.md、LICENSEを見つけることができませんでした。
それらを追加していただけないでしょうか？

**Comment by iris-s-coon** [comment]
@iris-s-coon が以下のラベルを提案し、適用しました：

- documentation
- help wanted
- good first issue

**Comment by iris-s-coon** [comment]
## 公式ドキュメント、CONTRIBUTING.md、LICENSEについて

README.mdを確認したところ、公式ドキュメント、CONTRIBUTING.md、LICENSEへのリンクは見つかりませんでした。

確かに、これらのファイルは開発者にとって非常に有用な情報源となります。

- **公式ドキュメント:** AIRAの使い方や機能について、詳細な情報を提供します。
- **CONTRIBUTING.md:** AIRAへの貢献方法を説明します。
- **LICENSE:** AIRAの利用規約を定めたものです。

開発者にとって、これらの情報が不足しているのは不便であるため、リポジトリにこれらのファイルを **追加することを強く推奨します。** 

## 提案

公式ドキュメントは、`docs/` ディレクトリ以下に配置することを提案します。 
CONTRIBUTING.md と LICENSE は、リポジトリのルートディレクトリに配置するのが一般的です。

これらのファイルを作成後、README.mdに適切なリンクを追加してください。 

## その他

README.md に記載されている `usage.md` は存在しないようです。もし存在する場合は、正しいリンクに修正してください。

## まとめ

リポジトリの使いやすさ向上のためにも、上記ファイルの追加を前向きにご検討ください。

**Comment by iris-s-coon** [comment]
## 変更提案

```diff
--- a/aira/aira.py
+++ b/aira/aira.py
@@ -186,6 +186,15 @@
             if self.repo_manager.is_initialized():
                 logger.info("Develop repository...")
                 self.gaiah_config["gaiah"] = self.merge_configs(self.gaiah_config["gaiah"], self.gaiah_config["gaiah"]["dev"])
+                
+                # CONTRIBUTING.mdとLICENSEを追加
+                for file in ["CONTRIBUTING.md", "LICENSE"]:
+                    source = os.path.join(".aira", "template", file)
+                    destination = os.path.join(self.gaiah_config["gaiah"]["local"]["repo_dir"], file)
+                    if not os.path.exists(destination):
+                        logger.info(f"Copying {file} to repository...")
+                        shutil.copy2(source, destination)
+            
             gaiah = Gaiah(self.gaiah_config)
             gaiah.run()  # Gaiahの実行
     

```

**Comment by Sunwood-ai-labs** [comment]
v0.4.0にて追加しました！

https://github.com/Sunwood-ai-labs/AIRA/releases/tag/v0.4.0
